dist: trusty
sudo: false
language: c
before_install: sudo apt install valgrind

compiler:
  - clang
  - gcc

script:
 - cmake .
 - scan-build make
 - cmake --build . -- -j2
 - ctest -j2
 - ctest -T memcheck
